consumerKey = "5dA5c6aCKS6pHU8Kz2Rnqt2Ht"
consumerSecret = "rteAS1lV9sNFkbMrR11n93mV3T7bD5NMS31utBnPoHa5HqzEYi"
accessToken = "765348591451967488-IhFy4M4pwLChsubplCB526Rk1Xvfqjq"
accessTokenSecret = "24kzoS1mplySlNbWQhUf105xJ8Ccql4mM85WPS0xPMRDB"

mongo_db_name = "dicdatabase"
twitter_latest_collection = "twitter_latest"
twitter_all_collection = "twitter_all"
reddit_latest_collection = "reddit_latest"
reddit_all_collection = "reddit_all"

twitter_latest_index = "twitter_latest"
twitter_all_index = "twitter_latest"
reddit_all_index = "reddit_latest"
reddit_latest_index = "reddit_latest"
